### ISSUE TITLE
Allow self signed certificates for Jira

### ISSUE THREAD

**Issue by jgmGit** [super-productivity/super-productivity#348]
I use the latest version of the superproductivity app version 5.0.12 on Ubuntu. I always get the following error when I try to connect

Jira: request to https://documentation.xxxxx.com/jira/rest/api/latest/myself failed, reason: unable to verify the first certificate

I upgraded from an older version something in the 2.x.x series, then this issue started to happen.  We use a self signed CA certificate at our company. 

Is there some way to ignore the ssl warnings ?

This is what I see in the log file

```
2020-04-27 13:51:15.317] [error] Frontend Error Stack: Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Jira: request to https://documentation.xxxxx.com/jira/rest/api/latest/issue/20411?expand=changelog,description failed, reason: unable to verify the first certificate"}
    at resolvePromise (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
    at file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:739:21
    at apply (file:///opt/superProductivity/resources/app.asar/dist/main.a2e485dba6df98cc850b.js:1:2331752)
    at t.invoke (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
    at Object.onInvoke (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27871:33)
    at t.invoke (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)
    at e.run (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)
    at apply (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:891:38)
    at t.invokeTask (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
    at Object.onInvokeTask (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27859:33) resolvePromise (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
```

**Comment by johannesjo** [comment]
Thanks for reporting. I provided an optional fix for this issue (you need to activate accepting self signed certificates in the jira config). Could you help me testing this?

**Comment by jgmGit** [comment]
Yes. I can help you with testing. What should I do ?

**Comment by johannesjo** [comment]
That's great. You need to follow the steps outlined here (including starting the electron app via `npm start`):
https://github.com/johannesjo/super-productivity#running-the-development-server

Once you got the app running you need to check if the new config option to ignore the certifcate error works for your setup.

**Comment by jgmGit** [comment]
How can I build the binary using the electron-builder, 

When I do ``yarn dist``  I get the following error. 
``00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'dist'
``
I can access it from the browser though, but to connect to the jira that I use, I need vpn. This is not working from the browser. So I was thinking of building the binary and testing.

**Comment by johannesjo** [comment]
Usually running `npm start`in  a seperate tab should be enough, to test it.

`yarn dist` should also work out of the box, but if not, have you tried creating the dist dictory manually via `mkdir dist` before executing `yarn dist`?

**Comment by jgmGit** [comment]
I get this error now :cry: 
```
TypeError: Cannot add property __modelVersion, object is not extensible
! Please copy & report !

TypeError: Cannot add property __modelVersion, object is not extensible
migrateTaskState (webpack:///src/app/features/tasks/migrate-task-state.util.ts:25:30)
MigrationService.push../src/app/core/migration/migration.service.ts.MigrationService._mTaskState (webpack:///src/app/core/migration/migration.service.ts:122:47)
MigrationService.push../src/app/core/migration/migration.service.ts.MigrationService._migrate (webpack:///src/app/core/migration/migration.service.ts:92:17)
this._isConfirmMigrateDialog (webpack:///src/app/core/migration/migration.service.ts:46:33)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:)
promise.then(function (webpack:///node_modules/rxjs/_esm5/internal/util/subscribeToPromise.js:7:)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:)
onInvoke (webpack:///node_modules/@angular/core/_ivy_ngcc_/fesm5/core.js:28245:)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:)
META: SP5.0.14 Browser – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium
```

If its not much of a trouble for you, could you build me a deb file for ubuntu, so i can test it easily. Or if there is a CI server, where I can take the binary from.

**Comment by johannesjo** [comment]
Here you go:
https://www.file-upload.net/download-14033431/superProductivity-5.0.14.AppImage.html

**Comment by jgmGit** [comment]
Hey it works. I was able to setup and was able to see the issues on Jira. Thank you :-)

**Comment by johannesjo** [comment]
Thanks for checking!

**Comment by jgmGit** [comment]
> I get this error now cry
> 
> ```
> TypeError: Cannot add property __modelVersion, object is not extensible
> ! Please copy & report !
> 
> TypeError: Cannot add property __modelVersion, object is not extensible
> migrateTaskState (webpack:///src/app/features/tasks/migrate-task-state.util.ts:25:30)
> MigrationService.push../src/app/core/migration/migration.service.ts.MigrationService._mTaskState (webpack:///src/app/core/migration/migration.service.ts:122:47)
> MigrationService.push../src/app/core/migration/migration.service.ts.MigrationService._migrate (webpack:///src/app/core/migration/migration.service.ts:92:17)
> this._isConfirmMigrateDialog (webpack:///src/app/core/migration/migration.service.ts:46:33)
> _next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:)
> next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:)
> promise.then(function (webpack:///node_modules/rxjs/_esm5/internal/util/subscribeToPromise.js:7:)
> invoke (webpack:///node_modules/zone.js/dist/zone.js:386:)
> onInvoke (webpack:///node_modules/@angular/core/_ivy_ngcc_/fesm5/core.js:28245:)
> invoke (webpack:///node_modules/zone.js/dist/zone.js:385:)
> META: SP5.0.14 Browser – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium
> ```
> 
> If its not much of a trouble for you, could you build me a deb file for ubuntu, so i can test it easily. Or if there is a CI server, where I can take the binary from.

I finally figured out what is going wrong. The issue is is was using `apt install cmdtest` to get `yarn`, instead I had to install from `npm`

As mentioned in here https://stackoverflow.com/a/52534824 
Could me nice if you could update the readme files, with it.

**Comment by johannesjo** [comment]
I would guess that this is most likely unrelated,  but I pushed a fix to master a couple of hours ago. 
https://github.com/johannesjo/super-productivity/commit/72fd7d0c977ec92062393830087940819332d9aa
Could this be it?

**Comment by jgmGit** [comment]
> I would guess that this is most likely unrelated, but I pushed a fix to master a couple of hours ago.
> [6b3056d](https://github.com/johannesjo/super-productivity/commit/6b3056db4e4328e5b5594cfa291b054915d9ad57)
> Could this be it?

yes i think

**Comment by hariudkmr** [comment]
i am getting error: self signed in certificate chain. can you please help me out resolve this issue

1. System - WINDOW OS
2. Super Productivity - 12.0.1

![Image](https://github.com/user-attachments/assets/3aef2ef7-f55b-4297-b32f-9ee247f56115)

Please find the attached image.

Thanks in advance.
Hari

**Comment by jnv** [comment]
Hello! Just wanted to report that I'm running into the same issue with although my context is a bit different:

- we use cloud-hosted Jira (on `*.atlassian.net`) with Atlassian-issued certificates
- the issue occurs with Cloudflare WARP enabled (VPN / tunnel), which, in our setup, acts as MITM so from application's point of view it forces a self-signed certificate

However, WARP does [install a root certificate](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/user-side-certificates/automated-deployment/) which I marked as trusted, therefore most applications, including browsers, don't complain about invalid certificate.

The "Allow self-signed certificate" option for Jira provider should work, unfortunately I don't see any checkbox in the configuration dialog for Jira. (Is it available in the latest version? Am I looking into wrong settings?)

What might also help (at least in case of WARP, but possibly in other corporate environments) would be for Super Productivity to respect system certificates. Node.js provides [`--use-system-ca`](https://nodejs.org/api/cli.html#--use-system-ca) option, but looks like Electron [doesn't support it](https://github.com/electron/electron/issues/45674).

**Comment by Zoriot** [comment]
Setting is back again so should work fine
